pingid: client is now a subclass of the PluginSDK provided MFAClient …
OneIdentity/safeguard-sessions-plugin-pingid pull request #3
Opened 2020-07-29 12:56 UTC by ddomeb

…class

Signed-off-by: Dome Darazs <dome.darazs@oneidentity.com>

2020-07-29 13:21 UTC, gorosz requested changes

2020-07-29 13:21 UTC, gorosz commented on lib/pingid.py
> +    def auth_offline(self, username, otp, session_id):
make this protected

2020-07-29 13:21 UTC, gorosz commented on lib/pingid.py
> +    def auth_online(self, username, device_id=None, request_otp=False, sp_name=None, sp_logo=None):
make this protected

2020-07-29 13:21 UTC, gorosz commented on lib/pingid.py
> +    def auth_start(self, username, device_id=None):
make this protected

2020-07-29 13:21 UTC, gorosz commented on lib/pingid.py
> +    def from_config(cls, configuration, device_id, push_display_text):
Can default params use for the new one: device_id=None?

2020-07-30 09:17 UTC, gasparb16 commented
LGTM

2020-07-30 09:35 UTC, ddomeb commented on lib/pingid.py
> +    def auth_start(self, username, device_id=None):
this must be called explicitly from plugin.py (line 74) so I'd rather leave it public.

2020-07-30 11:54 UTC, gorosz approved these changes

2020-07-30 12:02 UTC, merged